# The role of this Dockerfile is to use Atlasisan's native Confluence
# and add the Quick Reload.

# APP_VERSION: "7.19.0" or "8.9.0"
ARG APP_VERSION
# JDK: "jdk11" or "jdk17"
ARG JDK
# APPLE_SUFFIX: "-apple" or ""
ARG APPLE_SUFFIX

FROM atlassian/confluence:${APP_VERSION}-${JDK}${APPLE_SUFFIX}

# The quickreload.jar version. Must be after the "FROM" instruction, since "FROM" resets the args.
ARG QR_VERSION
# The file, otherwise MySQL drivers aren't available
ARG MYSQL_VERSION

RUN apt-get clean -y && apt-get update -y && apt-get install postgresql-client iputils-ping curl net-tools vim -y;
VOLUME /plugin

RUN mkdir -p                                      /var/atlassian/application-data/confluence/upmconfig/truststore
COPY ./tmp/upmconfig_truststore/truststore.jks    /var/atlassian/application-data/confluence/upmconfig/truststore/truststore.jks
RUN echo "atlassian.upm.signature.check.disabled=true" > /var/atlassian/application-data/confluence/upmconfig/upm.properties

RUN mkdir -p                                      /opt/atlassian/confluence/confluence/WEB-INF/atlassian-bundled-plugins/
RUN mkdir -p                                      /opt/atlassian/confluence/confluence/WEB-INF/lib/
COPY ./tmp/quickreload-${QR_VERSION}.jar          /opt/atlassian/confluence/confluence/WEB-INF/atlassian-bundled-plugins/quickreload.jar
COPY ./tmp/mysql-connector-j-${MYSQL_VERSION}.jar /opt/atlassian/confluence/confluence/WEB-INF/lib/mysql-connector-j-${MYSQL_VERSION}.jar
COPY ./tmp/quickreload.properties  /var/atlassian/application-data/confluence/quickreload.properties
RUN chown confluence:root /opt/atlassian/confluence/confluence/WEB-INF/atlassian-bundled-plugins/quickreload.jar
RUN chmod ug=rx,o= /opt/atlassian/confluence/confluence/WEB-INF/atlassian-bundled-plugins/quickreload.jar


RUN chown -R confluence:confluence /var/atlassian/application-data/confluence
RUN chown -R root:confluence       /var/atlassian/application-data/confluence/upmconfig
RUN chmod ug=rx,o=                 /var/atlassian/application-data/confluence/upmconfig
RUN chmod ug=rx,o=                 /var/atlassian/application-data/confluence/upmconfig/truststore
RUN chmod u=rw,g=r,o=              /var/atlassian/application-data/confluence/upmconfig/upm.properties
RUN chmod u=rw,g=r,o=              /var/atlassian/application-data/confluence/upmconfig/truststore/truststore.jks

RUN echo "log4j.logger.com.atlassian.velocity.htmlsafe.introspection=ERROR" >> /opt/atlassian/confluence/confluence/WEB-INF/classes/log4j.properties
RUN echo "log4j.logger.com.atlassian.confluence.cache=ERROR" >> /opt/atlassian/confluence/confluence/WEB-INF/classes/log4j.properties
RUN echo "log4j.logger.com.atlassian.confluence.plugins.synchrony=ERROR" >> /opt/atlassian/confluence/confluence/WEB-INF/classes/log4j.properties
